# Generated by Django 6.0.5 on 2026-05-19 18:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0003_agent_inquiry_propertyfeature_propertyimage_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='property',
            name='listing_type',
            field=models.CharField(choices=[('sale', 'For Sale'), ('rent', 'For Rent')], default='sale', max_length=10),
        ),
        migrations.AlterField(
            model_name='property',
            name='badge',
            field=models.CharField(blank=True, choices=[('luxury', 'Luxury'), ('new', 'New'), ('reduced', 'Reduced')], max_length=20, null=True),
        ),
    ]
