# Generated by Django 6.0.5 on 2026-05-19 19:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0004_property_listing_type_alter_property_badge'),
    ]

    operations = [
        migrations.CreateModel(
            name='ContactMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.CharField(blank=True, max_length=30)),
                ('interest', models.CharField(blank=True, choices=[('buying', 'Buying a Property'), ('selling', 'Selling a Property'), ('renting', 'Renting / Leasing'), ('investment', 'Investment Advice'), ('valuation', 'Property Valuation'), ('general', 'General Inquiry')], max_length=100)),
                ('subject', models.CharField(max_length=200)),
                ('message', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.AlterModelOptions(
            name='agent',
            options={'ordering': ['name']},
        ),
        migrations.AlterModelOptions(
            name='inquiry',
            options={'ordering': ['-created_at'], 'verbose_name_plural': 'Inquiries'},
        ),
        migrations.AlterModelOptions(
            name='property',
            options={'ordering': ['-featured', '-created_at'], 'verbose_name_plural': 'Properties'},
        ),
        migrations.AlterModelOptions(
            name='propertyfeature',
            options={'ordering': ['feature']},
        ),
        migrations.AlterModelOptions(
            name='propertyimage',
            options={'ordering': ['created_at']},
        ),
        migrations.AddField(
            model_name='property',
            name='agent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='properties', to='base.agent'),
        ),
        migrations.AddIndex(
            model_name='property',
            index=models.Index(fields=['listing_type', '-created_at'], name='base_proper_listing_fa89f0_idx'),
        ),
        migrations.AddIndex(
            model_name='property',
            index=models.Index(fields=['featured', '-created_at'], name='base_proper_feature_7058eb_idx'),
        ),
        migrations.AddIndex(
            model_name='property',
            index=models.Index(fields=['badge'], name='base_proper_badge_bf7e0c_idx'),
        ),
    ]
