# Generated by Django 6.0.5 on 2026-05-19 19:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0005_contactmessage_alter_agent_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='propertyimage',
            options={'ordering': ['sort_order', 'created_at']},
        ),
        migrations.AddField(
            model_name='propertyimage',
            name='caption',
            field=models.CharField(blank=True, max_length=120),
        ),
        migrations.AddField(
            model_name='propertyimage',
            name='photo_type',
            field=models.CharField(choices=[('exterior', 'Exterior'), ('living', 'Living Room'), ('bedroom', 'Bedroom'), ('bathroom', 'Bathroom'), ('kitchen', 'Kitchen'), ('pool', 'Pool'), ('view', 'View'), ('other', 'Other')], default='other', max_length=20),
        ),
        migrations.AddField(
            model_name='propertyimage',
            name='sort_order',
            field=models.PositiveSmallIntegerField(default=0),
        ),
    ]
