# Generated by Django 6.0.5 on 2026-05-25 09:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0006_alter_propertyimage_options_propertyimage_caption_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='agent',
            options={'ordering': ['name'], 'verbose_name': 'Agent', 'verbose_name_plural': 'Agents'},
        ),
        migrations.AddField(
            model_name='agent',
            name='linkedin',
            field=models.URLField(blank=True, help_text='Vendos linkun e plotë të profilit LinkedIn (p.sh. https://linkedin.com/in/emri)', null=True),
        ),
    ]
