# Generated by Django 6.0.5 on 2026-05-25 13:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0008_property_owner_favorite_message'),
    ]

    operations = [
        migrations.AlterField(
            model_name='agent',
            name='linkedin',
            field=models.URLField(blank=True, help_text='Enter the full LinkedIn profile URL, for example https://linkedin.com/in/name', null=True),
        ),
    ]
